name: Continuous Deployment(Production)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name : docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : docker buildx
        uses: docker/setup-buildx-action@v2

      - name : docker build and push image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/todo-app-gitops:${{ github.sha }}

      - name : clone the gitops repo, change the image tag and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/kumarchetan-1/argo-deployments.git
          cd argo-deployments

          sed -i 's|image: ${{ vars.DOCKER_USERNAME }}/todo-app-gitops.*|image: ${{ vars.DOCKER_USERNAME }}/todo-app-gitops:${{ github.sha }}|' manifest.yml
          git config user.name "Github Action Bot"
          git config user.email "actions@github.com" 

          git add .
          git commit -m "Update todod app's image tag to ${{github.sha}}"
          git push "https://${PAT}@github.com/kumarchetan-1/argo-deployments.git" main 
  