name: Continuous Deployment(Production)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name : docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : docker buildx
        uses: docker/setup-buildx-action@v2

      - name : docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-app-week39:${{ github.sha }}

      - name : clone staging ops repo, change the image tag and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/kumarchetan-1/argo-deployments.git
          cd argo-deployments

          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.sha }}|' k8s/todo-app.yaml
          git add .
          git commit -m "Update image tag to ${github.sha}"
          git push
