name: Continuous Deployment(Production)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name : docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : docker buildx
        uses: docker/setup-buildx-action@v2

      - name : docker build and push image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ vars.DOCKER_USERNAME }}/todo-app-week37:${{ github.sha }}

      - name: Export image URL 
        id: image_url
        run: echo "url=https://hub.docker.com/r/${{ vars.DOCKER_USERNAME }}/todo-app-week37:${{ github.sha }}" >> $GITHUB_OUTPUT
        
      - name: Print dockerhub link
        run: echo "Docker Hub Repo:${{ steps.image_url.outputs.url }}"